sudo: false

language: go

go:
  - 1.13.8

env:
  - GO111MODULE=on

go_import_path: github.com/WyattNielsen/mongoproxy

script:
  - go build -o mongoproxy mongoproxy.go
  - go test ./...
  - ./artifact.sh
